In [41]:
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import drive


train_dir = '/content/drive/MyDrive/data/data/train'
test_dir = '/content/drive/MyDrive/data/data/valid'
img_size, batch_size = (150, 150), 32

# Create and configure ImageDataGenerators
train_datagen = ImageDataGenerator(
    rescale=1./255, rotation_range=20, width_shift_range=0.2,
    height_shift_range=0.2, shear_range=0.2, zoom_range=0.2,
    horizontal_flip=True, fill_mode='nearest'
)
test_datagen = ImageDataGenerator(rescale=1./255)

# Create data generators
train_generator = train_datagen.flow_from_directory(
    train_dir, target_size=img_size, batch_size=batch_size, class_mode='categorical'
)
test_generator = test_datagen.flow_from_directory(
    test_dir, target_size=img_size, batch_size=batch_size, class_mode='categorical'
)

Found 1182 images belonging to 6 classes.
Found 329 images belonging to 6 classes.


In [42]:
train_dataset = '/content/drive/MyDrive/data/data/train'
valid_dataset = '/content/drive/MyDrive/data/data/valid'

In [43]:
print("Folders inside train directory:", os.listdir(train_dataset))
print("Folders inside valid directory:", os.listdir(valid_dataset))

Folders inside train directory: ['rottenoranges', 'rottenbanana', 'freshoranges', 'rottenapples', 'freshapples', 'freshbanana']
Folders inside valid directory: ['rottenbanana', 'rottenoranges', 'freshoranges', 'rottenapples', 'freshbanana', 'freshapples']


In [44]:
# Build the CNN model
# 6 neurons for the 6 fruit categories
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(6, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

# Train the model
epochs = 10
history = model.fit(
    train_generator,
    epochs=epochs,
    validation_data=test_generator
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)               │ (None, 148, 148, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 74, 74, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 72, 72, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 36, 36, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 82944)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │    10,616,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,637,126 (40.58 MB)

 Trainable params: 10,637,126 (40.58 MB)

 Non-trainable params: 0 (0.00 B)

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 42s 1s/step - accuracy: 0.2797 - loss: 3.2551 - val_accuracy: 0.6231 - val_loss: 1.0214
Epoch 2/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 37s 995ms/step - accuracy: 0.6205 - loss: 0.9896 - val_accuracy: 0.7325 - val_loss: 0.7962
Epoch 3/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 37s 996ms/step - accuracy: 0.7517 - loss: 0.7056 - val_accuracy: 0.7477 - val_loss: 0.7378
Epoch 4/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 37s 985ms/step - accuracy: 0.7210 - loss: 0.7541 - val_accuracy: 0.8389 - val_loss: 0.5582
Epoch 5/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 37s 984ms/step - accuracy: 0.8273 - loss: 0.4914 - val_accuracy: 0.8571 - val_loss: 0.4758
Epoch 6/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 37s 989ms/step - accuracy: 0.8203 - loss: 0.5168 - val_accuracy: 0.8754 - val_loss: 0.4432
Epoch 7/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 37s 995ms/step - accuracy: 0.8252 - loss: 0.4658 - val_accuracy: 0.8511 - val_loss: 0.4352
Epoch 8/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 37s 985ms/step - accuracy: 0.8419 - loss: 0.4291 - val_accurac

In [45]:
# Evaluate model performance
test_generator.reset()
predictions = model.predict(test_generator)
predicted_classes = np.argmax(predictions, axis=1)
true_classes = test_generator.classes
class_names = list(test_generator.class_indices.keys())

# Generate and print metrics
print("Classification Report:")
print(classification_report(true_classes, predicted_classes, target_names=class_names))
print("Confusion Matrix:")
print(confusion_matrix(true_classes, predicted_classes))

# Save predictions to a CSV file
filenames = test_generator.filenames
results = pd.DataFrame({'Filename': filenames, 'Prediction': [class_names[i] for i in predicted_classes]})
results.to_csv('fruit_predictions.csv', index=False)
print("\nPredictions saved to fruit_predictions.csv")

11/11 ━━━━━━━━━━━━━━━━━━━━ 3s 287ms/step
Classification Report:
               precision    recall  f1-score   support

  freshapples       0.24      0.24      0.24        50
  freshbanana       0.19      0.18      0.19        49
 freshoranges       0.23      0.23      0.23        43
 rottenapples       0.24      0.31      0.27        74
 rottenbanana       0.24      0.24      0.24        68
rottenoranges       0.28      0.16      0.20        45

     accuracy                           0.23       329
    macro avg       0.24      0.23      0.23       329
 weighted avg       0.24      0.23      0.23       329

Confusion Matrix:
[[12 11  5 11  8  3]
 [ 7  9  4 15 11  3]
 [ 7  3 10 13  9  1]
 [13  8 10 23 15  5]
 [ 7  8  8 23 16  6]
 [ 4  9  6 11  8  7]]

Predictions saved to fruit_predictions.csv
